In [1]:
import numpy as np
import pandas as pd
from scipy.spatial.transform import Rotation as R

# --------------------------------------------------
# 1. Load IMU trajectory (positions already integrated)
# --------------------------------------------------
imu = pd.read_csv("aligned_photo_imu.csv")

# Expected columns: filename, timestamp, pos_x, pos_y, pos_z
# If your CSV uses different names, update them here:
#imu_positions = imu[['pos_x', 'pos_y', 'pos_z']].values

imu.head(2)

photo           photo_time                 imu_time  \
0  IMG_2837.JPG  2025-10-15 16:37:00  2025-10-15 16:37:00.135   
1  IMG_2838.JPG  2025-10-15 16:37:06  2025-10-15 16:37:06.133   

   imu_time_diff_s  seconds_elapsed  gyroscope_z  gyroscope_y  gyroscope_x  \
0            0.135             15.0     0.053253    -0.019258    -0.004439   
1            0.133             21.0    -0.000501    -0.004474    -0.000432   

            gyroscope_local_time  gravity_z  ...  orientation_pitch  \
0  2025-10-15T16:37:00.135-07:00  -9.762937  ...          -0.066032   
1  2025-10-15T16:37:06.133-07:00  -9.712264  ...          -0.052304   

          orientation_local_time accelerometerUncalibrated_z  \
0  2025-10-15T16:37:00.135-07:00                   -0.987431   
1  2025-10-15T16:37:06.133-07:00                   -0.981831   

   accelerometerUncalibrated_y  accelerometerUncalibrated_x  \
0                     0.066210                    -0.063365   
1                     0.048635                    -0.123387   

   accelerometerUncalibrated_local_time accelerometer_z  accelerometer_y  \
0         2025-10-15T16:37:00.129-07:00        0.081532         0.001777   
1         2025-10-15T16:37:06.134-07:00        0.085508        -0.035216   

   accelerometer_x       accelerometer_local_time  
0         0.040302  2025-10-15T16:37:00.135-07:00  
1         0.046977  2025-10-15T16:37:06.133-07:00  

[2 rows x 52 columns]

In [2]:
import pandas as pd

imu = pd.read_csv("aligned_photo_imu.csv")
print("Columns:", imu.columns.tolist())
imu.head()


Columns: ['photo', 'photo_time', 'imu_time', 'imu_time_diff_s', 'seconds_elapsed', 'gyroscope_z', 'gyroscope_y', 'gyroscope_x', 'gyroscope_local_time', 'gravity_z', 'gravity_y', 'gravity_x', 'gravity_local_time', 'magnetometerUncalibrated_z', 'magnetometerUncalibrated_y', 'magnetometerUncalibrated_x', 'magnetometerUncalibrated_local_time', 'magnetometer_z', 'magnetometer_y', 'magnetometer_x', 'magnetometer_local_time', 'location_altitude', 'location_speedAccuracy', 'location_bearingAccuracy', 'location_latitude', 'location_altitudeAboveMeanSeaLevel', 'location_bearing', 'location_horizontalAccuracy', 'location_verticalAccuracy', 'location_longitude', 'location_speed', 'location_local_time', 'gyroscopeUncalibrated_z', 'gyroscopeUncalibrated_y', 'gyroscopeUncalibrated_x', 'gyroscopeUncalibrated_local_time', 'orientation_yaw', 'orientation_qx', 'orientation_qz', 'orientation_roll', 'orientation_qw', 'orientation_qy', 'orientation_pitch', 'orientation_local_time', 'accelerometerUncalibrate

photo           photo_time                 imu_time  \
0  IMG_2837.JPG  2025-10-15 16:37:00  2025-10-15 16:37:00.135   
1  IMG_2838.JPG  2025-10-15 16:37:06  2025-10-15 16:37:06.133   
2  IMG_2839.JPG  2025-10-15 16:37:10  2025-10-15 16:37:10.130   
3  IMG_2840.JPG  2025-10-15 16:37:14  2025-10-15 16:37:14.136   
4  IMG_2841.JPG  2025-10-15 16:37:19  2025-10-15 16:37:19.127   

   imu_time_diff_s  seconds_elapsed  gyroscope_z  gyroscope_y  gyroscope_x  \
0            0.135             15.0     0.053253    -0.019258    -0.004439   
1            0.133             21.0    -0.000501    -0.004474    -0.000432   
2            0.130             25.0     0.054564    -0.014750    -0.010651   
3            0.136             29.0     0.002471     0.011096     0.015074   
4            0.127             34.0    -0.021598     0.029419    -0.003451   

            gyroscope_local_time  gravity_z  ...  orientation_pitch  \
0  2025-10-15T16:37:00.135-07:00  -9.762937  ...          -0.066032   
1  2025-10-15T16:37:06.133-07:00  -9.712264  ...          -0.052304   
2  2025-10-15T16:37:10.130-07:00  -9.711562  ...          -0.061169   
3  2025-10-15T16:37:14.136-07:00  -9.680090  ...          -0.051588   
4  2025-10-15T16:37:19.127-07:00  -9.713937  ...           0.004962   

          orientation_local_time accelerometerUncalibrated_z  \
0  2025-10-15T16:37:00.135-07:00                   -0.987431   
1  2025-10-15T16:37:06.133-07:00                   -0.981831   
2  2025-10-15T16:37:10.130-07:00                   -0.982128   
3  2025-10-15T16:37:14.136-07:00                   -0.981021   
4  2025-10-15T16:37:19.127-07:00                   -0.979706   

   accelerometerUncalibrated_y  accelerometerUncalibrated_x  \
0                     0.066210                    -0.063365   
1                     0.048635                    -0.123387   
2                     0.059247                    -0.118700   
3                     0.049852                    -0.145714   
4                    -0.008347                    -0.131745   

   accelerometerUncalibrated_local_time accelerometer_z  accelerometer_y  \
0         2025-10-15T16:37:00.129-07:00        0.081532         0.001777   
1         2025-10-15T16:37:06.134-07:00        0.085508        -0.035216   
2         2025-10-15T16:37:10.131-07:00        0.074637        -0.013179   
3         2025-10-15T16:37:14.128-07:00        0.064177        -0.017768   
4         2025-10-15T16:37:19.129-07:00        0.113808        -0.035915   

   accelerometer_x       accelerometer_local_time  
0         0.040302  2025-10-15T16:37:00.135-07:00  
1         0.046977  2025-10-15T16:37:06.133-07:00  
2         0.057894  2025-10-15T16:37:10.130-07:00  
3         0.057161  2025-10-15T16:37:14.136-07:00  
4         0.052667  2025-10-15T16:37:19.127-07:00  

[5 rows x 52 columns]

In [3]:
from scipy.spatial.transform import Rotation as R
import numpy as np

def read_colmap_poses(path):
    poses = []
    with open(path) as f:
        for line in f:
            if line.startswith('#') or len(line.strip()) == 0:
                continue
            parts = line.strip().split()
            qw,qx,qy,qz = map(float, parts[1:5])
            tx,ty,tz = map(float, parts[5:8])
            Rwc = R.from_quat([qx,qy,qz,qw]).as_matrix().T
            twc = -Rwc @ np.array([tx,ty,tz])
            poses.append(twc)
            print(poses)
            print(len(poses))
    return np.array(poses)

colmap_centers = read_colmap_poses(r"C:\Users\vdeo3\Documents\Camera Scripts Python\colmap_project\images.txt")


[array([-1.39681632, -0.89054319,  2.33218893])]
1
[array([-1.39681632, -0.89054319,  2.33218893]), array([ 8361.75613359, -1388.79391009, -1798.91546965])]
2
[array([-1.39681632, -0.89054319,  2.33218893]), array([ 8361.75613359, -1388.79391009, -1798.91546965]), array([-2.82460412,  0.39618076, -6.29348353])]
3
[array([-1.39681632, -0.89054319,  2.33218893]), array([ 8361.75613359, -1388.79391009, -1798.91546965]), array([-2.82460412,  0.39618076, -6.29348353]), array([   1.        , -753.88433838,   -5.16027164])]
4
[array([-1.39681632, -0.89054319,  2.33218893]), array([ 8361.75613359, -1388.79391009, -1798.91546965]), array([-2.82460412,  0.39618076, -6.29348353]), array([   1.        , -753.88433838,   -5.16027164]), array([-1.49987847,  0.46995861,  0.05484122])]
5
[array([-1.39681632, -0.89054319,  2.33218893]), array([ 8361.75613359, -1388.79391009, -1798.91546965]), array([-2.82460412,  0.39618076, -6.29348353]), array([   1.        , -753.88433838,   -5.16027164]), array([-1

In [4]:
import pandas as pd
import numpy as np

imu = pd.read_csv("aligned_photo_imu.csv")

# --- convert timestamp strings to elapsed seconds ---
imu["imu_time"] = pd.to_datetime(imu["imu_time"])
ts = (imu["imu_time"] - imu["imu_time"].iloc[0]).dt.total_seconds().values

# --- gravity-corrected acceleration ---
accel = imu[["accelerometer_x","accelerometer_y","accelerometer_z"]].values
gvec  = imu[["gravity_x","gravity_y","gravity_z"]].values
acc_lin = (accel - gvec)* 9.81  #* 9.81  

# --- integrate acceleration twice ---
dt = np.mean(np.diff(ts))
vel = np.cumsum(acc_lin * dt, axis=0)
pos = np.cumsum(vel * dt, axis=0)
pos -= pos[0]

print("Δt mean:", dt, "seconds")
print("IMU positions shape:", pos.shape)
print("First few positions:\n", pos[:5])


Δt mean: 5.965241379310345 seconds
IMU positions shape: (30, 3)
First few positions:
 [[    0.             0.             0.        ]
 [  698.83944429  -416.52757243  6856.714809  ]
 [ 1844.35266653 -1046.92393518 17129.59662293]
 [ 3528.23811328 -1860.04416464 30804.00781642]
 [ 5698.18892909 -2668.71536864 47909.08889531]]


In [6]:
imu_names = imu["photo"].tolist()
imu_names

['IMG_2837.JPG',
 'IMG_2838.JPG',
 'IMG_2839.JPG',
 'IMG_2840.JPG',
 'IMG_2841.JPG',
 'IMG_2842.JPG',
 'IMG_2843.JPG',
 'IMG_2844.JPG',
 'IMG_2845.JPG',
 'IMG_2846.JPG',
 'IMG_2847.JPG',
 'IMG_2848.JPG',
 'IMG_2849.JPG',
 'IMG_2850.JPG',
 'IMG_2851.JPG',
 'IMG_2852.JPG',
 'IMG_2853.JPG',
 'IMG_2854.JPG',
 'IMG_2855.JPG',
 'IMG_2856.JPG',
 'IMG_2857.JPG',
 'IMG_2858.JPG',
 'IMG_2859.JPG',
 'IMG_2860.JPG',
 'IMG_2861.JPG',
 'IMG_2862.JPG',
 'IMG_2863.JPG',
 'IMG_2864.JPG',
 'IMG_2865.JPG',
 'IMG_2866.JPG']

In [7]:
# assuming each 'photo' in IMU CSV exists in COLMAP image list
colmap_names = []
with open(r"C:\Users\vdeo3\Documents\Camera Scripts Python\colmap_project\images.txt") as f:
    for line in f:
        if line.startswith('#'): continue
        parts = line.strip().split()
        if len(parts) > 9:
            colmap_names.append(parts[9])

# order COLMAP centers to match IMU file
order = [name for name in imu_names if name in colmap_names]
colmap_ordered = np.array([colmap_centers[colmap_names.index(n)] for n in order])

# truncate IMU positions to same length
imu_positions = pos[:len(colmap_ordered)]
print("Matched", len(imu_positions), "frames")
imu_positions

Matched 30 frames


array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.98839444e+02, -4.16527572e+02,  6.85671481e+03],
       [ 1.84435267e+03, -1.04692394e+03,  1.71295966e+04],
       [ 3.52823811e+03, -1.86004416e+03,  3.08040078e+04],
       [ 5.69818893e+03, -2.66871537e+03,  4.79090889e+04],
       [ 8.34933475e+03, -3.76882968e+03,  6.84313853e+04],
       [ 1.14251791e+04, -5.31135131e+03,  9.23545202e+04],
       [ 1.49894977e+04, -7.49081596e+03,  1.19636249e+05],
       [ 1.90985936e+04, -1.09486520e+04,  1.50080361e+05],
       [ 2.28809794e+04, -1.47081608e+04,  1.83966365e+05],
       [ 2.63345591e+04, -1.88882023e+04,  2.21269982e+05],
       [ 2.94654334e+04, -2.35248353e+04,  2.61993633e+05],
       [ 3.23731510e+04, -2.87335926e+04,  3.06048120e+05],
       [ 3.49404474e+04, -3.43202453e+04,  3.53528034e+05],
       [ 3.74740751e+04, -4.03204960e+04,  4.04453538e+05],
       [ 3.98766037e+04, -4.66695723e+04,  4.58831618e+05],
       [ 4.22619013e+04, -5.31425182e+04

In [8]:
def estimate_similarity_transform(A, B):
    """
    Estimate s, R, t that maps A -> B.
    A, B: Nx3 arrays (A = COLMAP, B = IMU)
    """
    mu_A, mu_B = A.mean(0), B.mean(0)
    A_c, B_c = A - mu_A, B - mu_B
    H = A_c.T @ B_c / len(A)
    U, S, Vt = np.linalg.svd(H)
    R_est = Vt.T @ U.T
    if np.linalg.det(R_est) < 0:
        Vt[-1, :] *= -1
        R_est = Vt.T @ U.T
    scale = np.trace(np.diag(S)) / np.sum(A_c**2)
    t_est = mu_B - scale * R_est @ mu_A
    return scale, R_est, t_est

scale, R_align, t_align = estimate_similarity_transform(colmap_ordered, imu_positions)
print("Scale:", scale)
print("Rotation:\n", R_align)
print("Translation:", t_align)


Scale: 1560.4282212466803
Rotation:
 [[ 0.66569502 -0.6443371   0.37640384]
 [-0.73312392 -0.65881195  0.16880795]
 [ 0.13921013 -0.38832527 -0.91094677]]
Translation: [ 36735.27369304 -54542.00205586 558868.98603697]


In [9]:
# import open3d as o3d

# pcd = o3d.io.read_point_cloud(r"C:\Users\vdeo3\Documents\Camera Scripts Python\colmap_project\dense -mesh.ply")
# points = np.asarray(pcd.points)
# true_scale = 1.0 / scale   
# points_metric = true_scale * (R_align @ points.T).T + t_align
# pcd.points = o3d.utility.Vector3dVector(points_metric)
# save_path = r"C:\Users\vdeo3\Documents\Camera Scripts Python\colmap_project\mesh_metric.ply"
# o3d.io.write_point_cloud(save_path, pcd)
# print("✅ Saved metric point cloud →", save_path)



In [10]:
# import open3d as o3d
# import numpy as np

# # --- Load the scaled point cloud or mesh ---
# pcd = o3d.io.read_point_cloud(r"C:\Users\vdeo3\Documents\Camera Scripts Python\colmap_project\mesh_metric.ply")

# # --- Compute axis-aligned bounding box (AABB) ---
# aabb = pcd.get_axis_aligned_bounding_box()
# min_bound = aabb.get_min_bound()
# max_bound = aabb.get_max_bound()

# # --- Compute dimensions ---
# dimensions = max_bound - min_bound  # X, Y, Z extents in meters

# print("📏 Object bounding box:")
# print(f"  X-width: {dimensions[0]:.4f} m  ({dimensions[0]*100:.1f} cm)")
# print(f"  Y-depth: {dimensions[1]:.4f} m  ({dimensions[1]*100:.1f} cm)")
# print(f"  Z-height: {dimensions[2]:.4f} m  ({dimensions[2]*100:.1f} cm)")

# # --- Optional: visualize bounding box ---
# aabb.color = (1, 0, 0)  # red box
# o3d.visualization.draw_geometries([pcd, aabb])


In [11]:
# print("Estimated scale:", scale)


In [12]:
import os, subprocess
import numpy as np
from scipy.spatial.transform import Rotation

# -------------------------------------------------------------------
# ✅ Paths (edit these if needed)
# -------------------------------------------------------------------
input_mesh = r"C:\Users\vdeo3\Documents\Camera Scripts Python\colmap_project\dense -mesh.ply"
output_mesh = r"C:\Users\vdeo3\Documents\Camera Scripts Python\colmap_project\mesh_metric.ply"
blender_exe = r"C:\Program Files\Blender Foundation\Blender 4.5\blender.exe"
blender_script = r"C:\Users\vdeo3\Documents\Camera Scripts Python\colmap_project\apply_blender_transform.py"

# -------------------------------------------------------------------
# ✅ Variables from your alignment code
# -------------------------------------------------------------------
# scale, R_align, t_align must already exist from previous cells

# -------------------------------------------------------------------
# ✅ Step 1: Write Blender helper script (UTF-8 safe)
# -------------------------------------------------------------------
if not os.path.exists(blender_script):
    blender_code = r"""
import bpy
import sys
import mathutils

# -------------------------------------------------------
# Parse args
# -------------------------------------------------------
args = sys.argv
input_path = args[-7]
output_path = args[-6]
scale_factor = float(args[-5])
rx, ry, rz = map(float, args[-4:-1])
tx, ty, tz = map(float, args[-3:])

print("Input:", input_path)
print("Output:", output_path)
print("Scale:", scale_factor)
print("Rotation (radians):", (rx, ry, rz))
print("Translation:", (tx, ty, tz))

# -------------------------------------------------------
# Import mesh
# -------------------------------------------------------
bpy.ops.import_mesh.ply(filepath=input_path)
obj = bpy.context.selected_objects[0]
mesh = obj.data

# -------------------------------------------------------
# Build full transformation matrix:  M = T * R * S
# -------------------------------------------------------
rot = mathutils.Euler((rx, ry, rz), 'XYZ').to_matrix().to_4x4()
trans = mathutils.Matrix.Translation((tx, ty, tz))
scale_mat = mathutils.Matrix.Scale(scale_factor, 4)
M = trans @ rot @ scale_mat

# -------------------------------------------------------
# Apply transform to every vertex (IMU = s R COLMAP + t)
# -------------------------------------------------------
for v in mesh.vertices:
    v.co = M @ v.co

# -------------------------------------------------------
# Reset object transform to identity and export
# -------------------------------------------------------
obj.matrix_world = mathutils.Matrix.Identity(4)
bpy.ops.export_mesh.ply(filepath=output_path)

# -------------------------------------------------------
# Sanity check: print final bounding box in meters
# -------------------------------------------------------
verts = [v.co for v in mesh.vertices]
min_v = mathutils.Vector((min(v.x for v in verts),
                          min(v.y for v in verts),
                          min(v.z for v in verts)))
max_v = mathutils.Vector((max(v.x for v in verts),
                          max(v.y for v in verts),
                          max(v.z for v in verts)))
size = max_v - min_v
print(f"✅ Saved metric mesh to: {output_path}")
print(f"Object bounding box (meters): X={size.x:.4f}, Y={size.y:.4f}, Z={size.z:.4f}")
"""
    with open(blender_script, "w", encoding="utf-8") as f:
        f.write(blender_code)
    print("✅ Blender helper script created at:", blender_script)
else:
    print("ℹ️ Using existing Blender script →", blender_script)

# -------------------------------------------------------------------
# ✅ Step 2: Convert rotation matrix to Euler angles for Blender
# -------------------------------------------------------------------
r_euler = Rotation.from_matrix(R_align).as_euler('xyz', degrees=False)

# -------------------------------------------------------------------
# ✅ Step 3: Run Blender in background mode
# -------------------------------------------------------------------
cmd = [
    blender_exe, "--background",
    "--python", blender_script, "--",
    input_mesh, output_mesh,
    str(scale),  # use scale directly (COLMAP → IMU)
    str(r_euler[0]), str(r_euler[1]), str(r_euler[2]),
    str(t_align[0]), str(t_align[1]), str(t_align[2])
]

print("🚀 Launching Blender 4.5.3 LTS for scaling and alignment...")
subprocess.run(cmd)
print("🎉 Done! Metric mesh exported to:", output_mesh)


ℹ️ Using existing Blender script → C:\Users\vdeo3\Documents\Camera Scripts Python\colmap_project\apply_blender_transform.py
🚀 Launching Blender 4.5.3 LTS for scaling and alignment...
🎉 Done! Metric mesh exported to: C:\Users\vdeo3\Documents\Camera Scripts Python\colmap_project\mesh_metric.ply


In [13]:
print("scale =", scale)
print("1/scale =", 1/scale)
print("Expected object width in meters:", 55e-3)
print("Scaled width (m):", 55e-3 * (1/scale))


scale = 1560.4282212466803
1/scale = 0.0006408497272633696
Expected object width in meters: 0.055
Scaled width (m): 3.524673499948533e-05


In [14]:
import open3d as o3d
import numpy as np

mesh = o3d.io.read_triangle_mesh(input_mesh)
points = np.asarray(mesh.vertices)

# Apply transform in Python to verify scale numerically
points_metric = scale * (R_align @ points.T).T + t_align
bbox = np.ptp(points_metric, axis=0)
print("Predicted bounding box (m):", bbox)
print("Width (mm):", bbox[0]*1000)


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
Predicted bounding box (m): [30464.83130977 20295.2501298  10166.97846057]
Width (mm): 30464831.30976618


In [15]:
fixed_scale = scale / 1000.0
points_metric = fixed_scale * (R_align @ points.T).T + t_align
bbox = np.ptp(points_metric, axis=0)
print("Fixed bounding box (m):", bbox)
print("Width (mm):", bbox[0]*1000)


Fixed bounding box (m): [30.46483131 20.29525013 10.16697846]
Width (mm): 30464.831309764122
